### ISSUE TITLE
parse error: Invalid numeric literal at line 1, column 6

### ISSUE THREAD

**Issue by adrianthedev** [shirobrak/action-phpcs#11]
I get this output `parse error: Invalid numeric literal at line 1, column 6` when I run it with `reporter: github-pr-review`. I'm using it on a pretty much standard laravel app.

Thank you!

```yml
name: Reviewdog

on: [pull_request]

jobs:phpcs:
    name: runner / phpcs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install phpcs
        run: composer global require "squizlabs/php_codesniffer=*"
      - name: phpcs
        uses: shirobrak/action-phpcs@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          phpcs_flags: '--standard=phpcs.xml app/'
```

![image](https://user-images.githubusercontent.com/1334409/102344835-2520ea80-3fa5-11eb-8db0-356971d2e9d2.png)
